### ISSUE TITLE
Raspberry 4B ARM64 not working

### ISSUE THREAD

**Issue by appleimperio** [patsoffice/docker-mjpg-streamer#1]
Hi I try to map the device I even put the container in privilege mode always ending with the same error "camera device, /dev/video0, does not exist" and I know the path exist because if I unplug the camera the /dev/video0 and even the rule I create for the camera both disappear. Thanks for your help!

**Comment by vicat47** [comment]
the shell script [start-mjpg-streame](https://github.com/patsoffice/docker-mjpg-streamer/blob/master/start-mjpg-streamer) line 7 `if` block has wrong file test operators
`if [ -f "${CAMERA_DEV}" ]`
but the video0 file is a character device, so the script should be
`if [ -c ${CAMERA_DEV}" ]`
